define({
    patient: "Paciente",
    sources: "Fuentes",
    orders: "Órdenes",
    favorites: "Favoritos",
    search: "Búsqueda",
    browse: "Navegar",
    prompt: "Aviso",
    view: "Vista",
    tools: "Instrumentos",
    currentencounter: "Actual Encuentro",
    small: "Pequeño",
    medium: "Medio",
    large: "Grande",
    dxprompt: "DX Aviso",
    nursingprompt: "Aviso de Enfermería",
    concise: "Conciso",
    expanded: "Expandido",
    design: "Diseño",
    flowsheet: "Flujo laminar",
    details: "Detalles",
    duplicate: "Duplicar",
    order: "Ordenar",
    addtofavorites: "Agregar a Favoritos",
    //delete: "Borrar",
    addtonote: "Añadir a la Nota",
    merge: "Unir",
    otherwisenormal: "Por lo Demás Normal",
    undootherwisenormal: "Deshacer lo Demás Normal",
    clearnonentered: "Claro que no Entró",
    clearall: "Borrar Todas Las",
    addfreetext: "Añadir Texto Libre",
    none: "Ninguno",
    bulletsbefore: "Balas Antes De",
    semicolonsafter: "Después de un Punto y Coma",
    contentlibrarymanager: "Gestor de Contenidos de la Biblioteca",
    emcalculator: "E&M Calculadora",
    account: "Cuenta",
    options: "Opciones",
    adminconsole: "Consola de Administración",
    medcinviewer: "Medcin Espectador",
    webservicetester: "Servicios Web Tester",
    quippeusersguide: "Quippe Guía del Usuario",
    newencounter: "Nueva Encuentro",
    openencounter: "Encuentro Abierto",
    savedraft: "Salvar el Proyecto",
    savefinalnote: "Ahorrar Nota Final",
    saveencounter: "Guardar Encuentro",
    printableview: "Ver Para Imprimir",
    logoff: "Finalizar la Sesión",
    applicationmenu: "Menú de Aplicación",
    deletefreetext: "Eliminar el Texto Libre",
    savecontent: "Guardar el Contenido",

    phrasing: "Fraseo",
    emanalysis: "E&M de Análisis",
    orderprocessor: "Procesador de Orden",
    mergeprompt: "Combinar del Sistema",
    concepts: "Conceptos",
    samplecustomcontent: "el contenido de muestra personalizada",
    more: "Más",
    loading: "Cargando",
    //menuitem: "Menu Item",
    contentlibrary: "Biblioteca de contenidos",
    personalcontent: "Contenido de Personal",
    years: "Años",//DateUtil still needs work
    months: "Mesas",
    weeks: "Semanas",
    day: "Día",
    uploadcontent: "Cargar contenido",//not working
    savecontent: "Guardar contenido",
    personalcontent: "Contenido de Personal",
    aboutquippe: "Acerca de Quippe",
    hpi: "HPI", //find out what this acronym means
    embrief: "Breve",//do these have technical terms in Spanish?
    emextended: "Ampliada",
    empertinent: "Pertinentes",
    emcomplete: "Complete",//
    emdetailed: "Detallada",
    emcomprehensive: "Integral",
    emstraight: "Straight",//
    emlow: "Bajo",
    emmoderate: "Moderado",
    emhigh: "Alto",
    emminimal: "Mínimo",
    emlimited: "Limited",//
    emmultiple: "Múltiples",
    emextensive: "Extensiva",
    emfocused: "centrado",
    emexpanded: "ampliado",
    yes: 'Sí',
    no: 'No',
    confirmdeletedialogtitle: 'Confirmar la Eliminación',
    confirmdeletecontentfolder: '¿Está seguro que desea eliminar la carpeta "{0}" y todo su contenido?',
    confirmdeletecontentitem: '¿Está seguro que desea eliminar el elemento "{0 }"?',

    //Finding details tab
    prefix: "Prefijo",
    modifier: "Modifier",//
    status: "Estado",
    value: "Valor",
    unit: "Unidad",
    note: "Nota",
    onset: "Inicio",
    duration: "Duración",
    episodes: "Episodes", 
    overridetext: "Anulación de texto", 

    // Finding phrasing tab 
    positive: "Positivo", 
    negative: "Negativo",
    independent: "Independiente", 
    dependent: "Dependiente", 
    useasdefault: "Utilizar como predeterminado", 
    addnewphrasing: "Añadir nueva redacción", 
    savechanges: "Guardar cambios", 
    deletephrasing: "Borrar", 

    // Content save dialog 
    location: "Ubicación", 
    name: "Nombre", 
    keywords: "Palabras clave", 
    type: "Tipo", 
    includeentrydetails: "Incluir detalles de la entrada", 
    includesectiongroupplacement: "Incluir la sección / grupo de la colocación", 
    makethismydefaulttemplate: "Establecer como mi plantilla por defecto", 
    list: "Lista", 
    template: "Plantilla", 
    savecontent: "Guardar contenido", 
    filename: "Nombre de archivo", 

    cmdOK: "OK", 
    cmdCancel: "Cancelar", 
    cmdUpload: "Subir", 

    tbNewFolder: "Nueva carpeta", 
    tbUpload: "Subir", 
    tbDownload: "Descargar", 
    tbRename: "Cambiar nombre", 
    tbDelete: "Borrar", 
    tbClose: "Cerrar", 

    nePatient: "Paciente", 
    neEncounterTime: "Tiempo de Encuentro", 
    neTemplate: "Plantilla", 
    oePatient: "Paciente", 
    oeEncounters: "Encuentros", 
    ppPrint: "Imprimir", 
    ppClose: "Cerrar", 

    uadFirstName: "Nombre", 
    uadLastName: "Last Name", 
    uadEmail: "Correo electrónico", 
    uadOrganization: "Organización", 
    uadAddress: "Dirección", 
    uadCity: "Ciudad", 
    uadState: "Estado", 
    uadPostalCode: "Código Postal", 
    uadCurrentPassword: "Contraseña actual", 
    uadNewPassword: "New Password",
    uadConfirm: "Confirmar",
    uadAccount: "Cuenta",
    uadContactInfo: "Datos de Contacto",
    uadPassword: "Contraseña"
});