define([
    "qc/PatientTaskPane",
    "qc/SourcesPane",
    "qc/OrdersPane",
    "qc/coding/SingleVocabTaskPane",
    "qc/coding/MultiVocabTaskPane",
    "qc/coding/CodingTaskPaneICD10",
    "qc/FavoritesPane",
    "qc/drawing/Toolbox",
    "qc/design/TaskPaneOverride",
    "qc/design/DesignPane",
    "qc/taskbar/DomainFilterPane",
    "qc/taskbar/SpecialtyFilterPane",
    "qc/taskbar/PrefixFilterPane",
    "qc/taskbar/TranslationPane",
    "qc/taskbar/BrowsePane",
    "qc/taskbar/FindingDetailsTaskPane"
], function () {
});